# Generated by Django 3.0.8 on 2020-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200802_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('is_end', models.BooleanField(default=False)),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
