# Generated by Django 3.0.8 on 2020-08-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200802_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='context',
            new_name='content',
        ),
    ]
